# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0004_auto_20180503_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_location',
        ),
    ]
