# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 04:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0006_auto_20180503_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Image_name',
            new_name='title',
        ),
    ]
