# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image_name', models.CharField(max_length=30)),
                ('Image_description', models.CharField(max_length=50)),
                ('Image_url', models.ImageField(upload_to='articles/')),
                ('source', models.CharField(max_length=20)),
            ],
        ),
    ]
