# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_auto_20180503_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snaps.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='categories',
            field=models.ManyToManyField(to='snaps.categories'),
        ),
    ]
